# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/freeglut-3.2.1/progs/WorldRMM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/freeglut-3.2.1/progs/WorldRMM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/freeglut-3.2.1/progs/WorldRMM/CMakeFiles /root/freeglut-3.2.1/progs/WorldRMM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/freeglut-3.2.1/progs/WorldRMM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named World

# Build rule for target.
World: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 World
.PHONY : World

# fast build rule for target.
World/fast:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/build
.PHONY : World/fast

SOIL.o: SOIL.c.o

.PHONY : SOIL.o

# target to build an object file
SOIL.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/SOIL.c.o
.PHONY : SOIL.c.o

SOIL.i: SOIL.c.i

.PHONY : SOIL.i

# target to preprocess a source file
SOIL.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/SOIL.c.i
.PHONY : SOIL.c.i

SOIL.s: SOIL.c.s

.PHONY : SOIL.s

# target to generate assembly for a file
SOIL.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/SOIL.c.s
.PHONY : SOIL.c.s

glmatrix.o: glmatrix.c.o

.PHONY : glmatrix.o

# target to build an object file
glmatrix.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/glmatrix.c.o
.PHONY : glmatrix.c.o

glmatrix.i: glmatrix.c.i

.PHONY : glmatrix.i

# target to preprocess a source file
glmatrix.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/glmatrix.c.i
.PHONY : glmatrix.c.i

glmatrix.s: glmatrix.c.s

.PHONY : glmatrix.s

# target to generate assembly for a file
glmatrix.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/glmatrix.c.s
.PHONY : glmatrix.c.s

image_DXT.o: image_DXT.c.o

.PHONY : image_DXT.o

# target to build an object file
image_DXT.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_DXT.c.o
.PHONY : image_DXT.c.o

image_DXT.i: image_DXT.c.i

.PHONY : image_DXT.i

# target to preprocess a source file
image_DXT.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_DXT.c.i
.PHONY : image_DXT.c.i

image_DXT.s: image_DXT.c.s

.PHONY : image_DXT.s

# target to generate assembly for a file
image_DXT.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_DXT.c.s
.PHONY : image_DXT.c.s

image_helper.o: image_helper.c.o

.PHONY : image_helper.o

# target to build an object file
image_helper.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_helper.c.o
.PHONY : image_helper.c.o

image_helper.i: image_helper.c.i

.PHONY : image_helper.i

# target to preprocess a source file
image_helper.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_helper.c.i
.PHONY : image_helper.c.i

image_helper.s: image_helper.c.s

.PHONY : image_helper.s

# target to generate assembly for a file
image_helper.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/image_helper.c.s
.PHONY : image_helper.c.s

stb_image_aug.o: stb_image_aug.c.o

.PHONY : stb_image_aug.o

# target to build an object file
stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/stb_image_aug.c.o
.PHONY : stb_image_aug.c.o

stb_image_aug.i: stb_image_aug.c.i

.PHONY : stb_image_aug.i

# target to preprocess a source file
stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/stb_image_aug.c.i
.PHONY : stb_image_aug.c.i

stb_image_aug.s: stb_image_aug.c.s

.PHONY : stb_image_aug.s

# target to generate assembly for a file
stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/stb_image_aug.c.s
.PHONY : stb_image_aug.c.s

world.o: world.c.o

.PHONY : world.o

# target to build an object file
world.c.o:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/world.c.o
.PHONY : world.c.o

world.i: world.c.i

.PHONY : world.i

# target to preprocess a source file
world.c.i:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/world.c.i
.PHONY : world.c.i

world.s: world.c.s

.PHONY : world.s

# target to generate assembly for a file
world.c.s:
	$(MAKE) -f CMakeFiles/World.dir/build.make CMakeFiles/World.dir/world.c.s
.PHONY : world.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... World"
	@echo "... edit_cache"
	@echo "... SOIL.o"
	@echo "... SOIL.i"
	@echo "... SOIL.s"
	@echo "... glmatrix.o"
	@echo "... glmatrix.i"
	@echo "... glmatrix.s"
	@echo "... image_DXT.o"
	@echo "... image_DXT.i"
	@echo "... image_DXT.s"
	@echo "... image_helper.o"
	@echo "... image_helper.i"
	@echo "... image_helper.s"
	@echo "... stb_image_aug.o"
	@echo "... stb_image_aug.i"
	@echo "... stb_image_aug.s"
	@echo "... world.o"
	@echo "... world.i"
	@echo "... world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

